include .env

clean: ## remove generated byte code, coverage reports, and build artifacts
	find . -name '__pycache__' -exec rm -rf {} +
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	rm -fr build/
	rm -fr dist/
	rm -fr *.egg-info

build:
	@docker compose build

up:
	@docker compose up

migrate:
	@docker compose exec app python scripts/wait_for_db.py
	@docker compose exec app python scripts/migrate.py

dev: build up migrate